# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
#include <iostream> //stdio.h
#include <map>
#include <locale.h>
using namespace std;

struct Materias{
	string codigo;
	string disciplina;
};

int main(){	
	setlocale(LC_ALL, "Portuguese");

	int chave;	
	char codigo[3];
	char disciplina[100]; 
	map<int, Materias> MapaLista;
	Materias mat;
	
	mat.codigo = "103";
	mat.disciplina = "Estrutura de Dados I";
	MapaLista[1] = mat;
	
	mat.codigo = "104";
	mat.disciplina = "Estrutura da Dados II";
	MapaLista[2] = mat;
	
	printf("Informe a chave da próxima disciplina: ");
	scanf("%d", &chave);
	printf("\nChave informada: %d", chave);	
	
	if (MapaLista.find(chave) != MapaLista.end()){
		cout<<"\nChave já cadastrada!"<<endl;		
	}else{		
		fflush(stdin);		
		printf("\nInforme o código da disciplina: ");
		gets(codigo);
		mat.codigo = codigo;
		
		printf("\nInforme o nome da disciplina: ");
		gets(disciplina);
		mat.disciplina = disciplina;
		fflush(stdin);
		MapaLista[chave] = mat;
	}
	printf("\nImpressão de todos dos elementos do mapa!\n");
	/*imprimir ******/
	for(unsigned int i = 1; i<=MapaLista.size(); i++){
		cout<<"\nCódigo: "+MapaLista[i].codigo +
			" Disciplina: "+MapaLista[i].disciplina<<endl;
	}	
	return 0;
}
